### ISSUE TITLE
Issue with Serde when running tests.

### ISSUE THREAD

**Issue by ian-k-thompson** [TatriX/realworld-rust-rocket#13]
![image](https://user-images.githubusercontent.com/1195692/58756360-b141fd00-853a-11e9-9b03-d800e2b834df.png)

Probably an incompatibility between the Serde version and something else.

**Comment by TatriX** [comment]
Thanks for the report! I should work now.

**Comment by ian-k-thompson** [comment]
Sweet, thanks for fixing so fast. I will pull master when I get home.
