### ISSUE TITLE
Getting articles returns the wrong articlesCount for pagination

### ISSUE THREAD

**Issue by SRugina** [TatriX/realworld-rust-rocket#16]
For realworld's pagination on any frontend, the `articlesCount` returned needs to be of all articles in the database, not of how many articles are returned as that is limited by the `limit` param.

The line below:
https://github.com/TatriX/realworld-rust-rocket/blob/f6b7166d227ca090f29512930329051922a905ab/src/routes/articles.rs#L57

returns only the count of how many articles will be sent to the client - i.e. the `limit` param that the client gives.

Compared to the Node.js backend:
`Article.count(query).exec(),`
[(permalink)](https://github.com/gothinkster/node-express-realworld-example-app/blob/ba04b70c31af81ca7935096740a6e083563b3a4a/routes/api/articles.js#L72)

which performs a separate request to count the articles in the database and returns that.

The solution is to perform a second request to count the articles. Although, since this project uses diesel and postgres, the [pagination example](https://github.com/diesel-rs/diesel/blob/v1.3.0/examples/postgres/advanced-blog-cli/src/pagination.rs) can be modified to perform this in one request.

**Comment by TatriX** [comment]
Thanks for pointing that out! I'll fix that when I'll have time. And of course PR is welcome.
