### ISSUE TITLE
Need Help for Tiberius Sample

### ISSUE THREAD

**Issue by yusrenaltair** [TatriX/realworld-rust-rocket#19]
I am a Rust newbie and I'm very interested in implementing Rust in the projects I am working on. I'm using SQL Server Database, only that provided by the company. But I am constrained in the Tiberius implementation (pure-rust TDS implementation).
If you have time to make an example of this realworld app with Tiberius, me and other people who have the same problem, will be very happy.
Thank you for your attention.

**Comment by TatriX** [comment]
Sorry, this is out of scope for this project and myself in particular.
