### ISSUE TITLE
Security best practices

### ISSUE THREAD

**Issue by phill-85** [TatriX/realworld-rust-rocket#28]
The advise is often given not to roll your own authentication. Does this code follow security best practices? Are there any crates that are audited that could be substituted?

**Comment by TatriX** [comment]
Hi!

> Does this code follow security best practices

I don't think so. This is out of scope for the project unless someone is willing to work on that.

> Are there any crates that are audited that could be substituted?

Sorry, I don't think I get that question.

**Comment by TatriX** [comment]
Feel free to reopen if needed.
