### ISSUE TITLE
Make diesel_cli installation clearer

### ISSUE THREAD

**Issue by Exegetech** [TatriX/realworld-rust-rocket#5]
As a Rust beginner I tried to install `diesel_cli` and it failed on my Mac.

Turns out because I only have PostgreSQL but not other databases. Maybe the Getting Started section on installing `diesel_cli` can be made clearer.

```
cargo install diesel_cli --no-default-features --features "postgres"
```

**Comment by TatriX** [comment]
Sure. Do you want to send a PR with this change?

**Comment by Exegetech** [comment]
Yup. Created the PR just now.

Also is there any plan for building the front end side of application?

**Comment by TatriX** [comment]
Thanks!
No, I don't have such plans.
